format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character"""

right_format = """$all"""

[character]
success_symbol = "[❯](bright-green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](bright-green)"

[username]
format = "[$user]($style)@"
show_always = false
style_user = "blue bold"

[hostname]
format = "[$hostname]($style) "
ssh_only = true
style = "bold green"

[directory]
before_repo_root_style = "blue"
truncation_length = 5
style = "blue bold"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "󰘬 "
style = "bright-green"

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "bright-yellow"
conflicted = "="
ahead = "⇡${count} "
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count} ⇣${behind_count}"
up_to_date = ""
untracked = "?${count} "
stashed = "$"
modified = "!${count} "
staged = "+${count} "
renamed = "»"
deleted = "✘${count} "

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 2000
